/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.10.0.111.2 */
/* Module Version: 5.7 */
/* Thu Feb 24 17:14:00 2022 */

/* parameterized module instance */
dds_pll __ (.CLKI( ), .CLKOP( ));
