/* Verilog netlist generated by SCUBA Diamond (64-bit) 3.10.0.111.2 */
/* Module Version: 1.6 */
/* D:\Program Files\lscc\diamond\3.10_x64\ispfpga\bin\nt64\scuba.exe -w -n dds_sin_table -lang verilog -synth lse -bus_exp 7 -bb -arch xo2c00 -type cosine -addr_width 8 -width 10 -pfu -input_reg -mode 0 -output_reg -area -pipeline 1  */
/* Thu Feb 24 17:09:37 2022 */


`timescale 1 ns / 1 ps
module dds_sin_table (Clock, ClkEn, Reset, Theta, Sine)/* synthesis NGD_DRC_MASK=1 */;
    input wire Clock;
    input wire ClkEn;
    input wire Reset;
    input wire [7:0] Theta;
    output wire [9:0] Sine;

    wire func_or_inet;
    wire lx_ne0;
    wire lx_ne0_inv;
    wire mx_ctrl_r_inv;
    wire rom_addr0_r;
    wire rom_addr0_r_1;
    wire rom_addr0_r_2;
    wire rom_addr0_r_3;
    wire rom_addr0_r_4;
    wire mx_ctrl_r;
    wire rom_addr0_r_5;
    wire mx_ctrl_r_1;
    wire rom_dout;
    wire rom_dout_1;
    wire rom_dout_2;
    wire rom_dout_3;
    wire rom_dout_4;
    wire rom_dout_5;
    wire rom_dout_6;
    wire rom_dout_7;
    wire rom_dout_8;
    wire sinromoutsel;
    wire rom_dout_9;
    wire out_sel_i;
    wire rom_dout_10;
    wire rom_dout_11;
    wire rom_dout_12;
    wire rom_dout_13;
    wire rom_dout_14;
    wire rom_dout_15;
    wire rom_dout_16;
    wire rom_dout_17;
    wire rom_dout_18;
    wire out_sel;
    wire rom_dout_19;
    wire sinout_pre;
    wire sinout_pre_1;
    wire sinout_pre_2;
    wire sinout_pre_3;
    wire sinout_pre_4;
    wire sinout_pre_5;
    wire sinout_pre_6;
    wire sinout_pre_7;
    wire sinout_pre_8;
    wire sinout_pre_9;
    wire rom_addr0_r_n;
    wire rom_addr0_r_inv;
    wire rom_addr0_r_n_1;
    wire rom_addr0_r_n_2;
    wire co0;
    wire rom_addr0_r_1_inv;
    wire rom_addr0_r_2_inv;
    wire rom_addr0_r_n_3;
    wire rom_addr0_r_n_4;
    wire co1;
    wire rom_addr0_r_3_inv;
    wire rom_addr0_r_4_inv;
    wire rom_addr0_r_n_5;
    wire co2;
    wire rom_addr0_r_5_inv;
    wire rom_dout_9_ffin;
    wire rom_dout_8_ffin;
    wire rom_dout_7_ffin;
    wire rom_dout_6_ffin;
    wire rom_dout_5_ffin;
    wire rom_dout_4_ffin;
    wire rom_dout_3_ffin;
    wire rom_dout_2_ffin;
    wire rom_dout_1_ffin;
    wire rom_dout_ffin;
    wire rom_addr0_r_n_6;
    wire rom_addr0_r_n_7;
    wire rom_addr0_r_n_8;
    wire rom_addr0_r_n_9;
    wire rom_addr0_r_n_10;
    wire rom_addr0_r_n_11;
    wire rom_dout_n;
    wire scuba_vhi;
    wire rom_dout_inv;
    wire rom_dout_n_1;
    wire rom_dout_n_2;
    wire co0_1;
    wire rom_dout_1_inv;
    wire rom_dout_2_inv;
    wire rom_dout_n_3;
    wire rom_dout_n_4;
    wire co1_1;
    wire rom_dout_3_inv;
    wire rom_dout_4_inv;
    wire rom_dout_n_5;
    wire rom_dout_n_6;
    wire co2_1;
    wire rom_dout_5_inv;
    wire rom_dout_6_inv;
    wire rom_dout_n_7;
    wire rom_dout_n_8;
    wire co3;
    wire rom_dout_7_inv;
    wire rom_dout_8_inv;
    wire rom_dout_n_9;
    wire co4;
    wire rom_dout_9_inv;
    wire scuba_vlo;

    INV INV_17 (.A(rom_addr0_r_5), .Z(rom_addr0_r_5_inv));

    INV INV_16 (.A(rom_addr0_r_4), .Z(rom_addr0_r_4_inv));

    INV INV_15 (.A(rom_addr0_r_3), .Z(rom_addr0_r_3_inv));

    INV INV_14 (.A(rom_addr0_r_2), .Z(rom_addr0_r_2_inv));

    INV INV_13 (.A(rom_addr0_r_1), .Z(rom_addr0_r_1_inv));

    INV INV_12 (.A(rom_addr0_r), .Z(rom_addr0_r_inv));

    INV INV_11 (.A(rom_dout_9), .Z(rom_dout_9_inv));

    INV INV_10 (.A(rom_dout_8), .Z(rom_dout_8_inv));

    INV INV_9 (.A(rom_dout_7), .Z(rom_dout_7_inv));

    INV INV_8 (.A(rom_dout_6), .Z(rom_dout_6_inv));

    INV INV_7 (.A(rom_dout_5), .Z(rom_dout_5_inv));

    INV INV_6 (.A(rom_dout_4), .Z(rom_dout_4_inv));

    INV INV_5 (.A(rom_dout_3), .Z(rom_dout_3_inv));

    INV INV_4 (.A(rom_dout_2), .Z(rom_dout_2_inv));

    INV INV_3 (.A(rom_dout_1), .Z(rom_dout_1_inv));

    INV INV_2 (.A(rom_dout), .Z(rom_dout_inv));

    defparam LUT4_1.initval =  16'hfffe ;
    ROM16X1A LUT4_1 (.AD3(rom_addr0_r_n_6), .AD2(rom_addr0_r_n_7), .AD1(rom_addr0_r_n_8), 
        .AD0(rom_addr0_r_n_9), .DO0(func_or_inet));

    defparam LUT4_0.initval =  16'hfffe ;
    ROM16X1A LUT4_0 (.AD3(func_or_inet), .AD2(rom_addr0_r_n_10), .AD1(rom_addr0_r_n_11), 
        .AD0(scuba_vlo), .DO0(lx_ne0));

    INV INV_1 (.A(lx_ne0), .Z(lx_ne0_inv));

    INV INV_0 (.A(mx_ctrl_r), .Z(mx_ctrl_r_inv));

    AND2 AND2_t0 (.A(mx_ctrl_r_inv), .B(lx_ne0_inv), .Z(out_sel_i));

    FD1P3DX FF_29 (.D(Theta[0]), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(rom_addr0_r))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_28 (.D(Theta[1]), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(rom_addr0_r_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_27 (.D(Theta[2]), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(rom_addr0_r_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_26 (.D(Theta[3]), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(rom_addr0_r_3))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_25 (.D(Theta[4]), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(rom_addr0_r_4))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_24 (.D(Theta[5]), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(rom_addr0_r_5))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_23 (.D(Theta[6]), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(mx_ctrl_r))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_22 (.D(Theta[7]), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(mx_ctrl_r_1))
             /* synthesis GSR="ENABLED" */;

    MUX21 muxb_25 (.D0(rom_addr0_r_n), .D1(rom_addr0_r), .SD(mx_ctrl_r), 
        .Z(rom_addr0_r_n_6));

    MUX21 muxb_24 (.D0(rom_addr0_r_n_1), .D1(rom_addr0_r_1), .SD(mx_ctrl_r), 
        .Z(rom_addr0_r_n_7));

    MUX21 muxb_23 (.D0(rom_addr0_r_n_2), .D1(rom_addr0_r_2), .SD(mx_ctrl_r), 
        .Z(rom_addr0_r_n_8));

    MUX21 muxb_22 (.D0(rom_addr0_r_n_3), .D1(rom_addr0_r_3), .SD(mx_ctrl_r), 
        .Z(rom_addr0_r_n_9));

    MUX21 muxb_21 (.D0(rom_addr0_r_n_4), .D1(rom_addr0_r_4), .SD(mx_ctrl_r), 
        .Z(rom_addr0_r_n_10));

    MUX21 muxb_20 (.D0(rom_addr0_r_n_5), .D1(rom_addr0_r_5), .SD(mx_ctrl_r), 
        .Z(rom_addr0_r_n_11));

    FD1P3DX FF_21 (.D(rom_dout_9_ffin), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(rom_dout_9))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_20 (.D(rom_dout_8_ffin), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(rom_dout_8))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_19 (.D(rom_dout_7_ffin), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(rom_dout_7))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_18 (.D(rom_dout_6_ffin), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(rom_dout_6))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_17 (.D(rom_dout_5_ffin), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(rom_dout_5))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_16 (.D(rom_dout_4_ffin), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(rom_dout_4))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_15 (.D(rom_dout_3_ffin), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(rom_dout_3))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_14 (.D(rom_dout_2_ffin), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(rom_dout_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_13 (.D(rom_dout_1_ffin), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(rom_dout_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_12 (.D(rom_dout_ffin), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(rom_dout))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_11 (.D(mx_ctrl_r_1), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(sinromoutsel))
             /* synthesis GSR="ENABLED" */;

    MUX21 muxb_19 (.D0(rom_dout), .D1(rom_dout_n), .SD(sinromoutsel), .Z(rom_dout_10));

    MUX21 muxb_18 (.D0(rom_dout_1), .D1(rom_dout_n_1), .SD(sinromoutsel), 
        .Z(rom_dout_11));

    MUX21 muxb_17 (.D0(rom_dout_2), .D1(rom_dout_n_2), .SD(sinromoutsel), 
        .Z(rom_dout_12));

    MUX21 muxb_16 (.D0(rom_dout_3), .D1(rom_dout_n_3), .SD(sinromoutsel), 
        .Z(rom_dout_13));

    MUX21 muxb_15 (.D0(rom_dout_4), .D1(rom_dout_n_4), .SD(sinromoutsel), 
        .Z(rom_dout_14));

    MUX21 muxb_14 (.D0(rom_dout_5), .D1(rom_dout_n_5), .SD(sinromoutsel), 
        .Z(rom_dout_15));

    MUX21 muxb_13 (.D0(rom_dout_6), .D1(rom_dout_n_6), .SD(sinromoutsel), 
        .Z(rom_dout_16));

    MUX21 muxb_12 (.D0(rom_dout_7), .D1(rom_dout_n_7), .SD(sinromoutsel), 
        .Z(rom_dout_17));

    MUX21 muxb_11 (.D0(rom_dout_8), .D1(rom_dout_n_8), .SD(sinromoutsel), 
        .Z(rom_dout_18));

    MUX21 muxb_10 (.D0(rom_dout_9), .D1(rom_dout_n_9), .SD(sinromoutsel), 
        .Z(rom_dout_19));

    FD1P3DX FF_10 (.D(out_sel_i), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(out_sel))
             /* synthesis GSR="ENABLED" */;

    MUX21 muxb_9 (.D0(rom_dout_10), .D1(scuba_vlo), .SD(out_sel), .Z(sinout_pre));

    MUX21 muxb_8 (.D0(rom_dout_11), .D1(scuba_vlo), .SD(out_sel), .Z(sinout_pre_1));

    MUX21 muxb_7 (.D0(rom_dout_12), .D1(scuba_vlo), .SD(out_sel), .Z(sinout_pre_2));

    MUX21 muxb_6 (.D0(rom_dout_13), .D1(scuba_vlo), .SD(out_sel), .Z(sinout_pre_3));

    MUX21 muxb_5 (.D0(rom_dout_14), .D1(scuba_vlo), .SD(out_sel), .Z(sinout_pre_4));

    MUX21 muxb_4 (.D0(rom_dout_15), .D1(scuba_vlo), .SD(out_sel), .Z(sinout_pre_5));

    MUX21 muxb_3 (.D0(rom_dout_16), .D1(scuba_vlo), .SD(out_sel), .Z(sinout_pre_6));

    MUX21 muxb_2 (.D0(rom_dout_17), .D1(scuba_vlo), .SD(out_sel), .Z(sinout_pre_7));

    MUX21 muxb_1 (.D0(rom_dout_18), .D1(scuba_vlo), .SD(out_sel), .Z(sinout_pre_8));

    MUX21 muxb_0 (.D0(rom_dout_19), .D1(scuba_vlo), .SD(out_sel), .Z(sinout_pre_9));

    FD1P3DX FF_9 (.D(sinout_pre), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(Sine[0]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_8 (.D(sinout_pre_1), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(Sine[1]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_7 (.D(sinout_pre_2), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(Sine[2]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_6 (.D(sinout_pre_3), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(Sine[3]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_5 (.D(sinout_pre_4), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(Sine[4]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_4 (.D(sinout_pre_5), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(Sine[5]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_3 (.D(sinout_pre_6), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(Sine[6]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_2 (.D(sinout_pre_7), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(Sine[7]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_1 (.D(sinout_pre_8), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(Sine[8]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_0 (.D(sinout_pre_9), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(Sine[9]))
             /* synthesis GSR="ENABLED" */;

    FADD2B neg_rom_addr0_r_n_0 (.A0(scuba_vlo), .A1(rom_addr0_r_inv), .B0(scuba_vlo), 
        .B1(scuba_vhi), .CI(scuba_vlo), .COUT(co0), .S0(), .S1(rom_addr0_r_n));

    FADD2B neg_rom_addr0_r_n_1 (.A0(rom_addr0_r_1_inv), .A1(rom_addr0_r_2_inv), 
        .B0(scuba_vlo), .B1(scuba_vlo), .CI(co0), .COUT(co1), .S0(rom_addr0_r_n_1), 
        .S1(rom_addr0_r_n_2));

    FADD2B neg_rom_addr0_r_n_2 (.A0(rom_addr0_r_3_inv), .A1(rom_addr0_r_4_inv), 
        .B0(scuba_vlo), .B1(scuba_vlo), .CI(co1), .COUT(co2), .S0(rom_addr0_r_n_3), 
        .S1(rom_addr0_r_n_4));

    FADD2B neg_rom_addr0_r_n_3 (.A0(rom_addr0_r_5_inv), .A1(scuba_vlo), 
        .B0(scuba_vlo), .B1(scuba_vlo), .CI(co2), .COUT(), .S0(rom_addr0_r_n_5), 
        .S1());

    defparam triglut_1_0_9.initval =  64'h0000000000000000 ;
    ROM64X1A triglut_1_0_9 (.AD5(rom_addr0_r_n_11), .AD4(rom_addr0_r_n_10), 
        .AD3(rom_addr0_r_n_9), .AD2(rom_addr0_r_n_8), .AD1(rom_addr0_r_n_7), 
        .AD0(rom_addr0_r_n_6), .DO0(rom_dout_9_ffin));

    defparam triglut_1_0_8.initval =  64'h0000000000000007 ;
    ROM64X1A triglut_1_0_8 (.AD5(rom_addr0_r_n_11), .AD4(rom_addr0_r_n_10), 
        .AD3(rom_addr0_r_n_9), .AD2(rom_addr0_r_n_8), .AD1(rom_addr0_r_n_7), 
        .AD0(rom_addr0_r_n_6), .DO0(rom_dout_8_ffin));

    defparam triglut_1_0_7.initval =  64'h000007FFFFFFFFF8 ;
    ROM64X1A triglut_1_0_7 (.AD5(rom_addr0_r_n_11), .AD4(rom_addr0_r_n_10), 
        .AD3(rom_addr0_r_n_9), .AD2(rom_addr0_r_n_8), .AD1(rom_addr0_r_n_7), 
        .AD0(rom_addr0_r_n_6), .DO0(rom_dout_7_ffin));

    defparam triglut_1_0_6.initval =  64'h003FF8003FFFFFF8 ;
    ROM64X1A triglut_1_0_6 (.AD5(rom_addr0_r_n_11), .AD4(rom_addr0_r_n_10), 
        .AD3(rom_addr0_r_n_9), .AD2(rom_addr0_r_n_8), .AD1(rom_addr0_r_n_7), 
        .AD0(rom_addr0_r_n_6), .DO0(rom_dout_6_ffin));

    defparam triglut_1_0_5.initval =  64'h07C1F81FC01FFFF8 ;
    ROM64X1A triglut_1_0_5 (.AD5(rom_addr0_r_n_11), .AD4(rom_addr0_r_n_10), 
        .AD3(rom_addr0_r_n_9), .AD2(rom_addr0_r_n_8), .AD1(rom_addr0_r_n_7), 
        .AD0(rom_addr0_r_n_6), .DO0(rom_dout_5_ffin));

    defparam triglut_1_0_4.initval =  64'h39CE38E3C3E07FF8 ;
    ROM64X1A triglut_1_0_4 (.AD5(rom_addr0_r_n_11), .AD4(rom_addr0_r_n_10), 
        .AD3(rom_addr0_r_n_9), .AD2(rom_addr0_r_n_8), .AD1(rom_addr0_r_n_7), 
        .AD0(rom_addr0_r_n_6), .DO0(rom_dout_4_ffin));

    defparam triglut_1_0_3.initval =  64'h5AD2DB64CCE387F8 ;
    ROM64X1A triglut_1_0_3 (.AD5(rom_addr0_r_n_11), .AD4(rom_addr0_r_n_10), 
        .AD3(rom_addr0_r_n_9), .AD2(rom_addr0_r_n_8), .AD1(rom_addr0_r_n_7), 
        .AD0(rom_addr0_r_n_6), .DO0(rom_dout_3_ffin));

    defparam triglut_1_0_2.initval =  64'hCE664D2D556D98F8 ;
    ROM64X1A triglut_1_0_2 (.AD5(rom_addr0_r_n_11), .AD4(rom_addr0_r_n_10), 
        .AD3(rom_addr0_r_n_9), .AD2(rom_addr0_r_n_8), .AD1(rom_addr0_r_n_7), 
        .AD0(rom_addr0_r_n_6), .DO0(rom_dout_2_ffin));

    defparam triglut_1_0_1.initval =  64'hAD5529987C36AB38 ;
    ROM64X1A triglut_1_0_1 (.AD5(rom_addr0_r_n_11), .AD4(rom_addr0_r_n_10), 
        .AD3(rom_addr0_r_n_9), .AD2(rom_addr0_r_n_8), .AD1(rom_addr0_r_n_7), 
        .AD0(rom_addr0_r_n_6), .DO0(rom_dout_1_ffin));

    defparam triglut_1_0_0.initval =  64'h780072AB832DF958 ;
    ROM64X1A triglut_1_0_0 (.AD5(rom_addr0_r_n_11), .AD4(rom_addr0_r_n_10), 
        .AD3(rom_addr0_r_n_9), .AD2(rom_addr0_r_n_8), .AD1(rom_addr0_r_n_7), 
        .AD0(rom_addr0_r_n_6), .DO0(rom_dout_ffin));

    VHI scuba_vhi_inst (.Z(scuba_vhi));

    FADD2B neg_rom_dout_n_0 (.A0(scuba_vlo), .A1(rom_dout_inv), .B0(scuba_vlo), 
        .B1(scuba_vhi), .CI(scuba_vlo), .COUT(co0_1), .S0(), .S1(rom_dout_n));

    FADD2B neg_rom_dout_n_1 (.A0(rom_dout_1_inv), .A1(rom_dout_2_inv), .B0(scuba_vlo), 
        .B1(scuba_vlo), .CI(co0_1), .COUT(co1_1), .S0(rom_dout_n_1), .S1(rom_dout_n_2));

    FADD2B neg_rom_dout_n_2 (.A0(rom_dout_3_inv), .A1(rom_dout_4_inv), .B0(scuba_vlo), 
        .B1(scuba_vlo), .CI(co1_1), .COUT(co2_1), .S0(rom_dout_n_3), .S1(rom_dout_n_4));

    FADD2B neg_rom_dout_n_3 (.A0(rom_dout_5_inv), .A1(rom_dout_6_inv), .B0(scuba_vlo), 
        .B1(scuba_vlo), .CI(co2_1), .COUT(co3), .S0(rom_dout_n_5), .S1(rom_dout_n_6));

    FADD2B neg_rom_dout_n_4 (.A0(rom_dout_7_inv), .A1(rom_dout_8_inv), .B0(scuba_vlo), 
        .B1(scuba_vlo), .CI(co3), .COUT(co4), .S0(rom_dout_n_7), .S1(rom_dout_n_8));

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    FADD2B neg_rom_dout_n_5 (.A0(rom_dout_9_inv), .A1(scuba_vlo), .B0(scuba_vlo), 
        .B1(scuba_vlo), .CI(co4), .COUT(), .S0(rom_dout_n_9), .S1());



    // exemplar begin
    // exemplar attribute FF_29 GSR ENABLED
    // exemplar attribute FF_28 GSR ENABLED
    // exemplar attribute FF_27 GSR ENABLED
    // exemplar attribute FF_26 GSR ENABLED
    // exemplar attribute FF_25 GSR ENABLED
    // exemplar attribute FF_24 GSR ENABLED
    // exemplar attribute FF_23 GSR ENABLED
    // exemplar attribute FF_22 GSR ENABLED
    // exemplar attribute FF_21 GSR ENABLED
    // exemplar attribute FF_20 GSR ENABLED
    // exemplar attribute FF_19 GSR ENABLED
    // exemplar attribute FF_18 GSR ENABLED
    // exemplar attribute FF_17 GSR ENABLED
    // exemplar attribute FF_16 GSR ENABLED
    // exemplar attribute FF_15 GSR ENABLED
    // exemplar attribute FF_14 GSR ENABLED
    // exemplar attribute FF_13 GSR ENABLED
    // exemplar attribute FF_12 GSR ENABLED
    // exemplar attribute FF_11 GSR ENABLED
    // exemplar attribute FF_10 GSR ENABLED
    // exemplar attribute FF_9 GSR ENABLED
    // exemplar attribute FF_8 GSR ENABLED
    // exemplar attribute FF_7 GSR ENABLED
    // exemplar attribute FF_6 GSR ENABLED
    // exemplar attribute FF_5 GSR ENABLED
    // exemplar attribute FF_4 GSR ENABLED
    // exemplar attribute FF_3 GSR ENABLED
    // exemplar attribute FF_2 GSR ENABLED
    // exemplar attribute FF_1 GSR ENABLED
    // exemplar attribute FF_0 GSR ENABLED
    // exemplar end

endmodule
