/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.10.0.111.2 */
/* Module Version: 1.6 */
/* Thu Feb 24 17:09:37 2022 */

/* parameterized module instance */
dds_sin_table __ (.Clock( ), .ClkEn( ), .Reset( ), .Theta( ), .Sine( ));
